apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solr-read-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: read
    repoURL: https://github.com/coolstim/infra-charts
    targetRevision: HEAD
  destination:
    namespace: my-solr-read
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=background