apiVersion: v1
kind: ServiceAccount
metadata:
  name: meh
# ---
# apiVersion: solr.apache.org/v1beta1
# kind: SolrCloud
# metadata:
#   name: testtim-solr
# spec:
#   busyBoxImage:
#     repository: library/busybox
#     tag: 1.28.0-glibc
#   customSolrKubeOptions:
#     ingressOptions:
#       annotations:
#         alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80,"HTTPS": 443}]'
#         alb.ingress.kubernetes.io/scheme: internal
#         alb.ingress.kubernetes.io/target-type: ip
#         alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000
#         alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
#         alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '15'
#         alb.ingress.kubernetes.io/healthcheck-path: /solr/#/
#       ingressClassName: alb
#     podOptions:
#       resources:
#         limits:
#           memory: 50Gi
#         requests:
#           cpu: '2'
#           memory: 35Gi
#       tolerations:
#         - effect: NoSchedule
#           key: dedicated
#           operator: Equal
#           value: solr
#   dataStorage:
#     persistent:
#       pvcTemplate:
#         spec:
#           resources:
#             requests:
#               storage: 10Gi
#           storageClassName: gp3-3000
#       reclaimPolicy: Retain
#   replicas: 3
#   solrAddressability:
#     commonServicePort: 80
#     external:
#       domainName: aws-dev.disqover.com
#       hideNodes: true
#       method: Ingress
#     podPort: 8983
#   solrImage:
#     repository: solr
#     tag: 9.2.0
#   solrJavaMem: '-Xms20g -Xmx32g'
#   solrLogLevel: INFO
#   updateStrategy:
#     method: Managed
#   zookeeperRef:
#     provided:
#       chroot: /
#       image:
#         pullPolicy: IfNotPresent
#         repository: pravega/zookeeper
#       replicas: 3
#       persistence:
#         annotations:
#           argocd.argoproj.io/sync-options: Prune=false
#         spec:
#           resources:
#             requests:
#               storage: 10Gi
#           storageClassName: gp3-3000
#       zookeeperPodPolicy:
#         tolerations:
#           - effect: NoSchedule
#             key: dedicated
#             operator: Equal
#             value: infra